apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-base
  namespace: argocd
spec:
  project: deployment-event-platform
  source:
    repoURL: https://github.com/punit144/test-repo.git
    targetRevision: main
    path: charts/platform-base
  destination:
    server: https://kubernetes.default.svc
    namespace: deployment-event-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
