apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: gateway-success-rate
  namespace: {{ .Values.namespace }}
spec:
  metrics:
  - name: success-rate
    interval: 20s
    count: 3
    successCondition: result >= 0
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: test
                image: busybox
                command: ["/bin/sh","-c"]
                args: ["echo 1"]
              restartPolicy: Never

