apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: local-selfsigned
  namespace: istio-system
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-root-ca
  namespace: istio-system
spec:
  isCA: true
  commonName: local-dev-ca
  secretName: local-root-ca
  issuerRef:
    name: local-selfsigned
    kind: Issuer

