apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: deployment-platform-cert
  namespace: {{ .Values.namespace }}
spec:
  secretName: deployment-platform-tls

  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer

  dnsNames:
    - {{ .Values.istio.host | quote }}

