apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: deployment-platform-cert
  namespace: deployment-event-platform
spec:
  secretName: deployment-platform-tls
  issuerRef:
    name: local-ca
    kind: ClusterIssuer
  commonName: deployment-platform.local
  dnsNames:
  - deployment-platform.local
