apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: deployment-platform-cert
  namespace: {{ .Values.namespace }}
spec:
  secretName: deployment-platform-tls
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.clusterIssuer }}
  dnsNames:
    - {{ .Values.istio.host | quote }}
