apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rollout.stableService }}
  namespace: {{ .Values.namespace }}
  labels:
    app: gateway
spec:
  selector:
    app: gateway
  ports:
    - port: {{ .Values.services.gateway.port }}
      targetPort: {{ .Values.services.gateway.port }}
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rollout.canaryService }}
  namespace: {{ .Values.namespace }}
  labels:
    app: gateway
spec:
  selector:
    app: gateway
  ports:
    - port: {{ .Values.services.gateway.port }}
      targetPort: {{ .Values.services.gateway.port }}
      name: http
