apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: deployment-platform
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*.{{ .Values.istio.host }}" # Allow all subdomains
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "*.{{ .Values.istio.host }}" # Allow all subdomains
      tls:
        mode: SIMPLE
        credentialName: deployment-platform-tls

---
# 1. Argo CD Route (argocd.deployment-platform.local)
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argocd-route
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - "argocd.{{ .Values.istio.host }}"
  gateways:
    - deployment-platform
  http:
    - route:
        - destination:
            host: argocd-server.argocd.svc.cluster.local
            port:
              number: 80 # Use insecure port internally (Istio handles TLS)

---
# 2. Grafana Route (grafana.deployment-platform.local)
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grafana-route
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - "grafana.{{ .Values.istio.host }}"
  gateways:
    - deployment-platform
  http:
    - route:
        - destination:
            host: kube-prometheus-grafana.monitoring.svc.cluster.local
            port:
              number: 80

---
# 3. Prometheus Route (prometheus.deployment-platform.local)
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: prometheus-route
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - "prometheus.{{ .Values.istio.host }}"
  gateways:
    - deployment-platform
  http:
    - route:
        - destination:
            host: kube-prometheus-kube-prome-prometheus.monitoring.svc.cluster.local
            port:
              number: 9090

---
# 4. Argo Rollouts Route (rollouts.deployment-platform.local)
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: rollouts-route
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - "rollouts.{{ .Values.istio.host }}"
  gateways:
    - deployment-platform
  http:
    - route:
        - destination:
            host: argo-rollouts-dashboard-service.argo-rollouts.svc.cluster.local
            port:
              number: 3100
