apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: deployment-platform
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.istio.host | quote }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: gateway
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - {{ .Values.istio.host | quote }}
  gateways:
    - deployment-platform
  http:
    - name: primary
      route:
        - destination:
            host: gateway
            subset: stable
          weight: 80
        - destination:
            host: gateway
            subset: canary
          weight: 20
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: gateway
  namespace: {{ .Values.namespace }}
spec:
  host: gateway
  subsets:
    - name: stable
      labels:
        app: gateway
    - name: canary
      labels:
        app: gateway
