apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: deployment-platform-cert
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  secretName: deployment-platform-tls
  issuerRef:
    name: local-ca-issuer
    kind: Issuer
    group: cert-manager.io
  commonName: {{ .Values.istio.host }}
  dnsNames:
    - {{ .Values.istio.host }}
    - "*.{{ .Values.istio.host }}"  # <--- ADD THIS (Wildcard support)
  privateKey:
    algorithm: RSA
    size: 2048
