apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deployment-event-platform
  namespace: argocd
spec:
  project: deployment-event-platform
  ignoreDifferences:
  - group: crd.projectcalico.org
    kind: NetworkPolicy
    jsonPointers:
      - /spec
  source:
    repoURL: https://github.com/punit144/test-repo.git
    targetRevision: main
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: deployment-event-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
