apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webapp.fullname" . }}
  labels: {{- include "webapp.labels" . | nindent 4 }}
  annotations:
    # --- Argo CD Image Updater annotations ------------------------
    argocd-image-updater.argoproj.io/image-list: webapp={{ .Values.image.repository }}
    argocd-image-updater.argoproj.io/webapp.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: argocd
    # --------------------------------------------------------------
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "webapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "webapp.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: webapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
